/*
Author: Kaspar Etter (https://kasparetter.com/)
Work: Explained from First Principles (https://ef1p.com/)
License: CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/)
*/

// Generated by ChatGPT 5.2 Thinking and refined by Claude Opus 4.5.
declare module 'text-fragments-polyfill/dist/fragment-generation-utils.js' {
    export const GenerateFragmentStatus: {
        SUCCESS: 0;
        INVALID_SELECTION: 1;
        AMBIGUOUS: 2;
        TIMEOUT: 3;
        EXECUTION_FAILED: 4;
    };

    export type GenerateFragmentStatusType = 0 | 1 | 2 | 3 | 4;

    export type TextFragment = {
        prefix?: string;
        textStart: string;
        textEnd?: string;
        suffix?: string;
    };

    export type GenerateFragmentResult = {
        status: GenerateFragmentStatusType;
        fragment?: TextFragment;
    };

    export function generateFragment(selection: Selection): GenerateFragmentResult;

    export function generateFragmentFromRange(range: Range): GenerateFragmentResult;
}
